### PR TITLE
ZNET-25-help-center-dev-create-article-resource

### PR DESCRIPTION
**Pull request by nsmmrs**
Relevant commit: 07ce394e6395ca42c55e44c0f44d42429d2c29bf

### CODE REVIEW

**Comment by nsmmrs** [comment]
[[Help Center] Dev - Create article resource](https://trello.com/c/2O9ItyXF/10204-help-center-dev-create-article-resource)

**Review by ealders — APPROVED** [review]

**Comment by nsmmrs** [comment]
[[Help Center] Dev - Create Video Resource](https://trello.com/c/i9yZWeTR/10205-help-center-dev-create-video-resource)

**Comment by nsmmrs** [comment]
[[Help Center] Confirm links go to new Help Center](https://trello.com/c/w9BWcNfl/10234-help-center-confirm-links-go-to-new-help-center)

**Comment by nsmmrs** [comment]
[[Help Center] Rename Related Feature dropdowns to Viewing Restriction](https://trello.com/c/qLklj1dm/10367-help-center-rename-related-feature-dropdowns-to-viewing-restriction)

**Review by ealders — APPROVED** [review]

**Pull request merged**
